name: Build & Deploy
on:
  push:
      branches: [ main ]
        workflow_dispatch:
        env:
          PAGES_REPO: 'casellado/ANAS_SafeHub_App'
          jobs:
            build-and-deploy:
                runs-on: ubuntu-latest
                    steps:
                          - uses: actions/checkout@v4
                                - uses: actions/setup-node@v4
                                        with:
                                                  node-version: '20'
                                                        - run: npm install
                                                              - run: npm run build
                                                                    - uses: peaceiris/actions-gh-pages@v3
                                                                            with:
                                                                                      personal_token: ${{ secrets.DEPLOY_TOKEN }}
                                                                                                external_repository: ${{ env.PAGES_REPO }}
                                                                                                          publish_branch: main
                                                                                                                    publish_dir: ./dist
                                                                                                                    
